// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addAccessToken.sql

package database

import (
	"context"
	"database/sql"
)

const addAccessToken = `-- name: AddAccessToken :one
UPDATE users
SET refreshToken = $2
WHERE username = $1
RETURNING id, username, password, created_at, updated_at, refreshtoken
`

type AddAccessTokenParams struct {
	Username     string
	Refreshtoken sql.NullString
}

func (q *Queries) AddAccessToken(ctx context.Context, arg AddAccessTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addAccessToken, arg.Username, arg.Refreshtoken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Refreshtoken,
	)
	return i, err
}
