// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addMedia.sql

package database

import (
	"context"
	"database/sql"
)

const addMedia = `-- name: AddMedia :one
INSERT INTO media (media_name, media_type, file_path, format, upload_date, follow_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type AddMediaParams struct {
	MediaName  string
	MediaType  string
	FilePath   string
	Format     string
	UploadDate sql.NullTime
	FollowID   sql.NullInt32
}

func (q *Queries) AddMedia(ctx context.Context, arg AddMediaParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addMedia,
		arg.MediaName,
		arg.MediaType,
		arg.FilePath,
		arg.Format,
		arg.UploadDate,
		arg.FollowID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
