// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delAccessToken.sql

package database

import (
	"context"
	"database/sql"
)

const delAccessToken = `-- name: DelAccessToken :one
UPDATE users
SET refreshToken = NULL
WHERE refreshToken = $1
RETURNING id, username, password, created_at, updated_at, refreshtoken
`

func (q *Queries) DelAccessToken(ctx context.Context, refreshtoken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, delAccessToken, refreshtoken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Refreshtoken,
	)
	return i, err
}
