// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delFavourite.sql

package database

import (
	"context"
)

const deleteFavourite = `-- name: DeleteFavourite :one
DELETE FROM favourites
WHERE user_id = $1 AND media_id = $2
RETURNING id, user_id, media_id, added_at
`

type DeleteFavouriteParams struct {
	UserID  int32
	MediaID int32
}

func (q *Queries) DeleteFavourite(ctx context.Context, arg DeleteFavouriteParams) (Favourite, error) {
	row := q.db.QueryRowContext(ctx, deleteFavourite, arg.UserID, arg.MediaID)
	var i Favourite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaID,
		&i.AddedAt,
	)
	return i, err
}
