// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getAllMedia.sql

package database

import (
	"context"
)

const getAllMedia = `-- name: GetAllMedia :many
SELECT id, media_name, media_type, file_path, format, upload_date, follow_id
FROM media
`

func (q *Queries) GetAllMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getAllMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaName,
			&i.MediaType,
			&i.FilePath,
			&i.Format,
			&i.UploadDate,
			&i.FollowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
