// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getUserByToken.sql

package database

import (
	"context"
	"database/sql"
)

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, username, password, created_at, updated_at, refreshtoken FROM users WHERE  refreshToken = $1
`

func (q *Queries) GetUserByToken(ctx context.Context, refreshtoken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, refreshtoken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Refreshtoken,
	)
	return i, err
}
