// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mediaFavourites.sql

package database

import (
	"context"
)

const getFavouritedMedia = `-- name: GetFavouritedMedia :one
SELECT COUNT(*)
FROM favourites
WHERE user_id = $1 AND media_id = $2
`

type GetFavouritedMediaParams struct {
	UserID  int32
	MediaID int32
}

func (q *Queries) GetFavouritedMedia(ctx context.Context, arg GetFavouritedMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFavouritedMedia, arg.UserID, arg.MediaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
