// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mediaFollows.sql

package database

import (
	"context"
)

const getFollowedMedia = `-- name: GetFollowedMedia :many
SELECT media.id, media.media_name, media.media_type, media.file_path, media.format, media.upload_date, media.follow_id
FROM media
JOIN follows ON media.id = follows.media_id
WHERE follows.user_id = 1
`

func (q *Queries) GetFollowedMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaName,
			&i.MediaType,
			&i.FilePath,
			&i.Format,
			&i.UploadDate,
			&i.FollowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
