// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: selectmedia.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getMedia = `-- name: GetMedia :many
SELECT media.id, media.media_name, media.media_type, media.file_path, media.file_size, media.duration, media.resolution, media.format, media.upload_date, media.thumbnail, media.tags, media.description, media.view_count, media.rating, media.follow_id
FROM media
JOIN favourites ON media.id = favourites.media_id
WHERE favourites.user_id = $1
`

func (q *Queries) GetMedia(ctx context.Context, userID int32) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, getMedia, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.MediaName,
			&i.MediaType,
			&i.FilePath,
			&i.FileSize,
			&i.Duration,
			&i.Resolution,
			&i.Format,
			&i.UploadDate,
			&i.Thumbnail,
			pq.Array(&i.Tags),
			&i.Description,
			&i.ViewCount,
			&i.Rating,
			&i.FollowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
